version: '3'

services:
  falcon-service:
    image: falcon-service
    build: .
    env_file:
      - ../kdrive.env
    ports:
      - 8080:8080
    depends_on:
      - rabbitmq
     
  rabbitmq:
      image: rabbitmq:3-management-alpine
      container_name: rabbitmq
      ports:
        - 5672:5672
        - 15672:15672

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.5.0"
    environment:
      - discovery.type=single-node
    container_name: elasticsearch
    ports:
      - "9200:9200"
    healthcheck:
      test:
        - CMD
        - curl
        - "-f"
        - "http://localhost:9200"
      interval: 5s
      timeout: 10s
      retries: 5

  mongo:
    image: mongo:4.0.9
    ports:
      - "27017:27017"